#include "text_mode.h"

#define IDT_SIZE 256

void panic_handler(int i) {
    vga_clear_screen();
    fprint("\n");
    error("hihihaha the mr. interrupt hihi: ");
    fprint("%d", i);
    for (;;);
}

void tramplin_0() { panic_handler(0x0); }
void tramplin_1() { panic_handler(0x1); }
void tramplin_2() { panic_handler(0x2); }
void tramplin_3() { panic_handler(0x3); }
void tramplin_4() { panic_handler(0x4); }
void tramplin_5() { panic_handler(0x5); }
void tramplin_6() { panic_handler(0x6); }
void tramplin_7() { panic_handler(0x7); }
void tramplin_8() { panic_handler(0x8); }
void tramplin_9() { panic_handler(0x9); }
void tramplin_a() { panic_handler(0xa); }
void tramplin_b() { panic_handler(0xb); }
void tramplin_c() { panic_handler(0xc); }
void tramplin_d() { panic_handler(0xd); }
void tramplin_e() { panic_handler(0xe); }
void tramplin_f() { panic_handler(0xf); }
void tramplin_10() { panic_handler(0x10); }
void tramplin_11() { panic_handler(0x11); }
void tramplin_12() { panic_handler(0x12); }
void tramplin_13() { panic_handler(0x13); }
void tramplin_14() { panic_handler(0x14); }
void tramplin_15() { panic_handler(0x15); }
void tramplin_16() { panic_handler(0x16); }
void tramplin_17() { panic_handler(0x17); }
void tramplin_18() { panic_handler(0x18); }
void tramplin_19() { panic_handler(0x19); }
void tramplin_1a() { panic_handler(0x1a); }
void tramplin_1b() { panic_handler(0x1b); }
void tramplin_1c() { panic_handler(0x1c); }
void tramplin_1d() { panic_handler(0x1d); }
void tramplin_1e() { panic_handler(0x1e); }
void tramplin_1f() { panic_handler(0x1f); }
void tramplin_20() { panic_handler(0x20); }
void tramplin_21() { panic_handler(0x21); }
void tramplin_22() { panic_handler(0x22); }
void tramplin_23() { panic_handler(0x23); }
void tramplin_24() { panic_handler(0x24); }
void tramplin_25() { panic_handler(0x25); }
void tramplin_26() { panic_handler(0x26); }
void tramplin_27() { panic_handler(0x27); }
void tramplin_28() { panic_handler(0x28); }
void tramplin_29() { panic_handler(0x29); }
void tramplin_2a() { panic_handler(0x2a); }
void tramplin_2b() { panic_handler(0x2b); }
void tramplin_2c() { panic_handler(0x2c); }
void tramplin_2d() { panic_handler(0x2d); }
void tramplin_2e() { panic_handler(0x2e); }
void tramplin_2f() { panic_handler(0x2f); }
void tramplin_30() { panic_handler(0x30); }
void tramplin_31() { panic_handler(0x31); }
void tramplin_32() { panic_handler(0x32); }
void tramplin_33() { panic_handler(0x33); }
void tramplin_34() { panic_handler(0x34); }
void tramplin_35() { panic_handler(0x35); }
void tramplin_36() { panic_handler(0x36); }
void tramplin_37() { panic_handler(0x37); }
void tramplin_38() { panic_handler(0x38); }
void tramplin_39() { panic_handler(0x39); }
void tramplin_3a() { panic_handler(0x3a); }
void tramplin_3b() { panic_handler(0x3b); }
void tramplin_3c() { panic_handler(0x3c); }
void tramplin_3d() { panic_handler(0x3d); }
void tramplin_3e() { panic_handler(0x3e); }
void tramplin_3f() { panic_handler(0x3f); }
void tramplin_40() { panic_handler(0x40); }
void tramplin_41() { panic_handler(0x41); }
void tramplin_42() { panic_handler(0x42); }
void tramplin_43() { panic_handler(0x43); }
void tramplin_44() { panic_handler(0x44); }
void tramplin_45() { panic_handler(0x45); }
void tramplin_46() { panic_handler(0x46); }
void tramplin_47() { panic_handler(0x47); }
void tramplin_48() { panic_handler(0x48); }
void tramplin_49() { panic_handler(0x49); }
void tramplin_4a() { panic_handler(0x4a); }
void tramplin_4b() { panic_handler(0x4b); }
void tramplin_4c() { panic_handler(0x4c); }
void tramplin_4d() { panic_handler(0x4d); }
void tramplin_4e() { panic_handler(0x4e); }
void tramplin_4f() { panic_handler(0x4f); }
void tramplin_50() { panic_handler(0x50); }
void tramplin_51() { panic_handler(0x51); }
void tramplin_52() { panic_handler(0x52); }
void tramplin_53() { panic_handler(0x53); }
void tramplin_54() { panic_handler(0x54); }
void tramplin_55() { panic_handler(0x55); }
void tramplin_56() { panic_handler(0x56); }
void tramplin_57() { panic_handler(0x57); }
void tramplin_58() { panic_handler(0x58); }
void tramplin_59() { panic_handler(0x59); }
void tramplin_5a() { panic_handler(0x5a); }
void tramplin_5b() { panic_handler(0x5b); }
void tramplin_5c() { panic_handler(0x5c); }
void tramplin_5d() { panic_handler(0x5d); }
void tramplin_5e() { panic_handler(0x5e); }
void tramplin_5f() { panic_handler(0x5f); }
void tramplin_60() { panic_handler(0x60); }
void tramplin_61() { panic_handler(0x61); }
void tramplin_62() { panic_handler(0x62); }
void tramplin_63() { panic_handler(0x63); }
void tramplin_64() { panic_handler(0x64); }
void tramplin_65() { panic_handler(0x65); }
void tramplin_66() { panic_handler(0x66); }
void tramplin_67() { panic_handler(0x67); }
void tramplin_68() { panic_handler(0x68); }
void tramplin_69() { panic_handler(0x69); }
void tramplin_6a() { panic_handler(0x6a); }
void tramplin_6b() { panic_handler(0x6b); }
void tramplin_6c() { panic_handler(0x6c); }
void tramplin_6d() { panic_handler(0x6d); }
void tramplin_6e() { panic_handler(0x6e); }
void tramplin_6f() { panic_handler(0x6f); }
void tramplin_70() { panic_handler(0x70); }
void tramplin_71() { panic_handler(0x71); }
void tramplin_72() { panic_handler(0x72); }
void tramplin_73() { panic_handler(0x73); }
void tramplin_74() { panic_handler(0x74); }
void tramplin_75() { panic_handler(0x75); }
void tramplin_76() { panic_handler(0x76); }
void tramplin_77() { panic_handler(0x77); }
void tramplin_78() { panic_handler(0x78); }
void tramplin_79() { panic_handler(0x79); }
void tramplin_7a() { panic_handler(0x7a); }
void tramplin_7b() { panic_handler(0x7b); }
void tramplin_7c() { panic_handler(0x7c); }
void tramplin_7d() { panic_handler(0x7d); }
void tramplin_7e() { panic_handler(0x7e); }
void tramplin_7f() { panic_handler(0x7f); }
void tramplin_80() { panic_handler(0x80); }
void tramplin_81() { panic_handler(0x81); }
void tramplin_82() { panic_handler(0x82); }
void tramplin_83() { panic_handler(0x83); }
void tramplin_84() { panic_handler(0x84); }
void tramplin_85() { panic_handler(0x85); }
void tramplin_86() { panic_handler(0x86); }
void tramplin_87() { panic_handler(0x87); }
void tramplin_88() { panic_handler(0x88); }
void tramplin_89() { panic_handler(0x89); }
void tramplin_8a() { panic_handler(0x8a); }
void tramplin_8b() { panic_handler(0x8b); }
void tramplin_8c() { panic_handler(0x8c); }
void tramplin_8d() { panic_handler(0x8d); }
void tramplin_8e() { panic_handler(0x8e); }
void tramplin_8f() { panic_handler(0x8f); }
void tramplin_90() { panic_handler(0x90); }
void tramplin_91() { panic_handler(0x91); }
void tramplin_92() { panic_handler(0x92); }
void tramplin_93() { panic_handler(0x93); }
void tramplin_94() { panic_handler(0x94); }
void tramplin_95() { panic_handler(0x95); }
void tramplin_96() { panic_handler(0x96); }
void tramplin_97() { panic_handler(0x97); }
void tramplin_98() { panic_handler(0x98); }
void tramplin_99() { panic_handler(0x99); }
void tramplin_9a() { panic_handler(0x9a); }
void tramplin_9b() { panic_handler(0x9b); }
void tramplin_9c() { panic_handler(0x9c); }
void tramplin_9d() { panic_handler(0x9d); }
void tramplin_9e() { panic_handler(0x9e); }
void tramplin_9f() { panic_handler(0x9f); }
void tramplin_a0() { panic_handler(0xa0); }
void tramplin_a1() { panic_handler(0xa1); }
void tramplin_a2() { panic_handler(0xa2); }
void tramplin_a3() { panic_handler(0xa3); }
void tramplin_a4() { panic_handler(0xa4); }
void tramplin_a5() { panic_handler(0xa5); }
void tramplin_a6() { panic_handler(0xa6); }
void tramplin_a7() { panic_handler(0xa7); }
void tramplin_a8() { panic_handler(0xa8); }
void tramplin_a9() { panic_handler(0xa9); }
void tramplin_aa() { panic_handler(0xaa); }
void tramplin_ab() { panic_handler(0xab); }
void tramplin_ac() { panic_handler(0xac); }
void tramplin_ad() { panic_handler(0xad); }
void tramplin_ae() { panic_handler(0xae); }
void tramplin_af() { panic_handler(0xaf); }
void tramplin_b0() { panic_handler(0xb0); }
void tramplin_b1() { panic_handler(0xb1); }
void tramplin_b2() { panic_handler(0xb2); }
void tramplin_b3() { panic_handler(0xb3); }
void tramplin_b4() { panic_handler(0xb4); }
void tramplin_b5() { panic_handler(0xb5); }
void tramplin_b6() { panic_handler(0xb6); }
void tramplin_b7() { panic_handler(0xb7); }
void tramplin_b8() { panic_handler(0xb8); }
void tramplin_b9() { panic_handler(0xb9); }
void tramplin_ba() { panic_handler(0xba); }
void tramplin_bb() { panic_handler(0xbb); }
void tramplin_bc() { panic_handler(0xbc); }
void tramplin_bd() { panic_handler(0xbd); }
void tramplin_be() { panic_handler(0xbe); }
void tramplin_bf() { panic_handler(0xbf); }
void tramplin_c0() { panic_handler(0xc0); }
void tramplin_c1() { panic_handler(0xc1); }
void tramplin_c2() { panic_handler(0xc2); }
void tramplin_c3() { panic_handler(0xc3); }
void tramplin_c4() { panic_handler(0xc4); }
void tramplin_c5() { panic_handler(0xc5); }
void tramplin_c6() { panic_handler(0xc6); }
void tramplin_c7() { panic_handler(0xc7); }
void tramplin_c8() { panic_handler(0xc8); }
void tramplin_c9() { panic_handler(0xc9); }
void tramplin_ca() { panic_handler(0xca); }
void tramplin_cb() { panic_handler(0xcb); }
void tramplin_cc() { panic_handler(0xcc); }
void tramplin_cd() { panic_handler(0xcd); }
void tramplin_ce() { panic_handler(0xce); }
void tramplin_cf() { panic_handler(0xcf); }
void tramplin_d0() { panic_handler(0xd0); }
void tramplin_d1() { panic_handler(0xd1); }
void tramplin_d2() { panic_handler(0xd2); }
void tramplin_d3() { panic_handler(0xd3); }
void tramplin_d4() { panic_handler(0xd4); }
void tramplin_d5() { panic_handler(0xd5); }
void tramplin_d6() { panic_handler(0xd6); }
void tramplin_d7() { panic_handler(0xd7); }
void tramplin_d8() { panic_handler(0xd8); }
void tramplin_d9() { panic_handler(0xd9); }
void tramplin_da() { panic_handler(0xda); }
void tramplin_db() { panic_handler(0xdb); }
void tramplin_dc() { panic_handler(0xdc); }
void tramplin_dd() { panic_handler(0xdd); }
void tramplin_de() { panic_handler(0xde); }
void tramplin_df() { panic_handler(0xdf); }
void tramplin_e0() { panic_handler(0xe0); }
void tramplin_e1() { panic_handler(0xe1); }
void tramplin_e2() { panic_handler(0xe2); }
void tramplin_e3() { panic_handler(0xe3); }
void tramplin_e4() { panic_handler(0xe4); }
void tramplin_e5() { panic_handler(0xe5); }
void tramplin_e6() { panic_handler(0xe6); }
void tramplin_e7() { panic_handler(0xe7); }
void tramplin_e8() { panic_handler(0xe8); }
void tramplin_e9() { panic_handler(0xe9); }
void tramplin_ea() { panic_handler(0xea); }
void tramplin_eb() { panic_handler(0xeb); }
void tramplin_ec() { panic_handler(0xec); }
void tramplin_ed() { panic_handler(0xed); }
void tramplin_ee() { panic_handler(0xee); }
void tramplin_ef() { panic_handler(0xef); }
void tramplin_f0() { panic_handler(0xf0); }
void tramplin_f1() { panic_handler(0xf1); }
void tramplin_f2() { panic_handler(0xf2); }
void tramplin_f3() { panic_handler(0xf3); }
void tramplin_f4() { panic_handler(0xf4); }
void tramplin_f5() { panic_handler(0xf5); }
void tramplin_f6() { panic_handler(0xf6); }
void tramplin_f7() { panic_handler(0xf7); }
void tramplin_f8() { panic_handler(0xf8); }
void tramplin_f9() { panic_handler(0xf9); }
void tramplin_fa() { panic_handler(0xfa); }
void tramplin_fb() { panic_handler(0xfb); }
void tramplin_fc() { panic_handler(0xfc); }
void tramplin_fd() { panic_handler(0xfd); }
void tramplin_fe() { panic_handler(0xfe); }
void tramplin_ff() { panic_handler(0xff); }
void* tramplins[IDT_SIZE] = { tramplin_0, tramplin_1, tramplin_2, tramplin_3, tramplin_4, tramplin_5, tramplin_6, tramplin_7, tramplin_8, tramplin_9, tramplin_a, tramplin_b, tramplin_c, tramplin_d, tramplin_e, tramplin_f, tramplin_10, tramplin_11, tramplin_12, tramplin_13, tramplin_14, tramplin_15, tramplin_16, tramplin_17, tramplin_18, tramplin_19, tramplin_1a, tramplin_1b, tramplin_1c, tramplin_1d, tramplin_1e, tramplin_1f, tramplin_20, tramplin_21, tramplin_22, tramplin_23, tramplin_24, tramplin_25, tramplin_26, tramplin_27, tramplin_28, tramplin_29, tramplin_2a, tramplin_2b, tramplin_2c, tramplin_2d, tramplin_2e, tramplin_2f, tramplin_30, tramplin_31, tramplin_32, tramplin_33, tramplin_34, tramplin_35, tramplin_36, tramplin_37, tramplin_38, tramplin_39, tramplin_3a, tramplin_3b, tramplin_3c, tramplin_3d, tramplin_3e, tramplin_3f, tramplin_40, tramplin_41, tramplin_42, tramplin_43, tramplin_44, tramplin_45, tramplin_46, tramplin_47, tramplin_48, tramplin_49, tramplin_4a, tramplin_4b, tramplin_4c, tramplin_4d, tramplin_4e, tramplin_4f, tramplin_50, tramplin_51, tramplin_52, tramplin_53, tramplin_54, tramplin_55, tramplin_56, tramplin_57, tramplin_58, tramplin_59, tramplin_5a, tramplin_5b, tramplin_5c, tramplin_5d, tramplin_5e, tramplin_5f, tramplin_60, tramplin_61, tramplin_62, tramplin_63, tramplin_64, tramplin_65, tramplin_66, tramplin_67, tramplin_68, tramplin_69, tramplin_6a, tramplin_6b, tramplin_6c, tramplin_6d, tramplin_6e, tramplin_6f, tramplin_70, tramplin_71, tramplin_72, tramplin_73, tramplin_74, tramplin_75, tramplin_76, tramplin_77, tramplin_78, tramplin_79, tramplin_7a, tramplin_7b, tramplin_7c, tramplin_7d, tramplin_7e, tramplin_7f, tramplin_80, tramplin_81, tramplin_82, tramplin_83, tramplin_84, tramplin_85, tramplin_86, tramplin_87, tramplin_88, tramplin_89, tramplin_8a, tramplin_8b, tramplin_8c, tramplin_8d, tramplin_8e, tramplin_8f, tramplin_90, tramplin_91, tramplin_92, tramplin_93, tramplin_94, tramplin_95, tramplin_96, tramplin_97, tramplin_98, tramplin_99, tramplin_9a, tramplin_9b, tramplin_9c, tramplin_9d, tramplin_9e, tramplin_9f, tramplin_a0, tramplin_a1, tramplin_a2, tramplin_a3, tramplin_a4, tramplin_a5, tramplin_a6, tramplin_a7, tramplin_a8, tramplin_a9, tramplin_aa, tramplin_ab, tramplin_ac, tramplin_ad, tramplin_ae, tramplin_af, tramplin_b0, tramplin_b1, tramplin_b2, tramplin_b3, tramplin_b4, tramplin_b5, tramplin_b6, tramplin_b7, tramplin_b8, tramplin_b9, tramplin_ba, tramplin_bb, tramplin_bc, tramplin_bd, tramplin_be, tramplin_bf, tramplin_c0, tramplin_c1, tramplin_c2, tramplin_c3, tramplin_c4, tramplin_c5, tramplin_c6, tramplin_c7, tramplin_c8, tramplin_c9, tramplin_ca, tramplin_cb, tramplin_cc, tramplin_cd, tramplin_ce, tramplin_cf, tramplin_d0, tramplin_d1, tramplin_d2, tramplin_d3, tramplin_d4, tramplin_d5, tramplin_d6, tramplin_d7, tramplin_d8, tramplin_d9, tramplin_da, tramplin_db, tramplin_dc, tramplin_dd, tramplin_de, tramplin_df, tramplin_e0, tramplin_e1, tramplin_e2, tramplin_e3, tramplin_e4, tramplin_e5, tramplin_e6, tramplin_e7, tramplin_e8, tramplin_e9, tramplin_ea, tramplin_eb, tramplin_ec, tramplin_ed, tramplin_ee, tramplin_ef, tramplin_f0, tramplin_f1, tramplin_f2, tramplin_f3, tramplin_f4, tramplin_f5, tramplin_f6, tramplin_f7, tramplin_f8, tramplin_f9, tramplin_fa, tramplin_fb, tramplin_fc, tramplin_fd, tramplin_fe, tramplin_ff };
